import React, { createContext, useContext, useState, useEffect } from 'react';
import { INITIAL_PROJECTS } from '../data/projects';

const MuseumContext = createContext(null);

const STORAGE_KEY    = 'arch_museum_projects_v2';
const ADMIN_KEY      = 'arch_admin_session';
export const ADMIN_PASS = 'arch2026'; // ← change this

export function MuseumProvider({ children }) {
  const [projects, setProjects] = useState(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      return saved ? JSON.parse(saved) : INITIAL_PROJECTS;
    } catch { return INITIAL_PROJECTS; }
  });

  const safeGetAdmin = () => {
    try { return localStorage.getItem(ADMIN_KEY) === 'true'; }
    catch { return false; }
  };

  const [isAdmin,       setIsAdmin]       = useState(safeGetAdmin);
  const [adminPanel,    setAdminPanel]    = useState(false);
  const [editingProject, setEditingProject] = useState(null);
  const [viewingProject, setViewingProject] = useState(null);

  useEffect(() => {
    try { localStorage.setItem(STORAGE_KEY, JSON.stringify(projects)); } catch {}
  }, [projects]);

  const login = (pass) => {
    if (pass === ADMIN_PASS) {
      setIsAdmin(true);
      try { localStorage.setItem(ADMIN_KEY, 'true'); } catch {}
      return true;
    }
    return false;
  };

  const logout = () => {
    setIsAdmin(false);
    try { localStorage.removeItem(ADMIN_KEY); } catch {}
    setAdminPanel(false);
  };

  const [githubToken, setGithubToken] = useState(() => {
    try { return localStorage.getItem('arch_github_token') || ''; } catch { return ''; }
  });

  useEffect(() => {
    try {
      if (githubToken) localStorage.setItem('arch_github_token', githubToken);
      else localStorage.removeItem('arch_github_token');
    } catch {}
  }, [githubToken]);

  const pushToGithub = async (newProjects) => {
    if (!githubToken) return;
    try {
      const owner = 'NAJDAWI-dot';
      const repo = 'digital-museum';
      const path = 'src/data/projects.js';
      
      const getRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
        headers: { Authorization: `Bearer ${githubToken}` }
      });
      const getJson = await getRes.json();
      
      const fileContent = `// Auto-generated by Museum Editor\nexport const INITIAL_PROJECTS = ${JSON.stringify(newProjects, null, 2)};\n`;
      
      // Handle unicode base64 encoding correctly
      const encodedContent = btoa(new TextEncoder().encode(fileContent).reduce((data, byte) => data + String.fromCharCode(byte), ''));

      await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
        method: 'PUT',
        headers: { Authorization: `Bearer ${githubToken}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: 'chore: auto-update projects from live editor',
          content: encodedContent,
          sha: getJson.sha
        })
      });
    } catch (e) {
      console.error('Auto-sync failed:', e);
    }
  };

  const addProject    = (p) => { 
    const np = { ...p, id: `p${Date.now()}` }; 
    setProjects(prev => { const arr = [np, ...prev]; pushToGithub(arr); return arr; }); 
    return np; 
  };
  const updateProject = (id, u) => setProjects(prev => {
    const arr = prev.map(p => p.id === id ? { ...p, ...u } : p);
    pushToGithub(arr); return arr;
  });
  const deleteProject = (id) => setProjects(prev => {
    const arr = prev.filter(p => p.id !== id);
    pushToGithub(arr); return arr;
  });
  const moveProject   = (fromIdx, toIdx) => setProjects(prev => {
    const arr = [...prev];
    const [m] = arr.splice(fromIdx, 1);
    arr.splice(toIdx, 0, m);
    pushToGithub(arr); return arr;
  });

  const resetToDefaults = () => {
    if (confirm('Reset all projects to factory defaults? This cannot be undone.')) {
      setProjects(INITIAL_PROJECTS);
      pushToGithub(INITIAL_PROJECTS);
    }
  };

  return (
    <MuseumContext.Provider value={{
      projects, addProject, updateProject, deleteProject, moveProject, resetToDefaults,
      isAdmin, login, logout,
      adminPanel, setAdminPanel,
      editingProject, setEditingProject,
      viewingProject, setViewingProject,
      githubToken, setGithubToken
    }}>
      {children}
    </MuseumContext.Provider>
  );
}

export const useMuseum = () => useContext(MuseumContext);
